<?php
// CSV Report Download - ICT Head only
require_once __DIR__ . '/../config/constants.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/functions.php';

requireLogin();
if ($_SESSION['user_type'] !== 'staff' || ($_SESSION['staff_role'] !== ROLE_ICT_HEAD && $_SESSION['staff_role'] !== ROLE_ADMIN)) {
    setFlash('error', 'Unauthorized access.');
    $redir = ($_SESSION['staff_role'] ?? '') === ROLE_ADMIN ? '/admin/dashboard' : '/staff/dashboard';
    header('Location: ' . APP_URL . $redir);
    exit;
}

$pdo      = getDB();
$dateFrom = $_GET['from'] ?? date('Y-m-d', strtotime('-7 days'));
$dateTo   = $_GET['to']   ?? date('Y-m-d');

$stmt = $pdo->prepare("
    SELECT
        t.ticket_number   AS 'Ticket No',
        u.name            AS 'Raised By',
        u.department      AS 'Department',
        COALESCE(pc.name,'Custom') AS 'Category',
        t.custom_description AS 'Description',
        t.priority        AS 'Priority',
        t.status          AS 'Status',
        s.name            AS 'Assigned To',
        s.designation     AS 'Assignee Role',
        t.created_at      AS 'Created',
        t.solved_at       AS 'Solved',
        TIMESTAMPDIFF(HOUR, t.created_at, t.solved_at) AS 'Resolution Hours',
        f.rating          AS 'Feedback Rating',
        f.comment         AS 'Feedback Comment'
    FROM tickets t
    LEFT JOIN users u  ON t.user_id = u.id
    LEFT JOIN problem_categories pc ON t.problem_category_id = pc.id
    LEFT JOIN it_staff s ON t.assigned_to = s.id
    LEFT JOIN feedback f ON f.ticket_id = t.id
    WHERE t.created_at BETWEEN ? AND DATE_ADD(?, INTERVAL 1 DAY)
    ORDER BY t.created_at DESC
");
$stmt->execute([$dateFrom, $dateTo]);
$rows = $stmt->fetchAll();

// Stream CSV
$filename = 'TMS_Report_' . date('Ymd', strtotime($dateFrom)) . '_to_' . date('Ymd', strtotime($dateTo)) . '.csv';

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-cache, no-store, must-revalidate');

$output = fopen('php://output', 'w');

// UTF-8 BOM for Excel compatibility
fwrite($output, "\xEF\xBB\xBF");

// Header row
if (!empty($rows)) {
    fputcsv($output, array_keys($rows[0]));
} else {
    fputcsv($output, ['Ticket No','Raised By','Department','Category','Description',
                       'Priority','Status','Assigned To','Assignee Role',
                       'Created','Solved','Resolution Hours','Feedback Rating','Feedback Comment']);
}

// Data rows
foreach ($rows as $row) {
    fputcsv($output, $row);
}

// Summary footer
fputcsv($output, []);
fputcsv($output, ['--- SUMMARY ---']);
fputcsv($output, ['Report Period', $dateFrom . ' to ' . $dateTo]);
fputcsv($output, ['Total Tickets', count($rows)]);
$solved = count(array_filter($rows, fn($r) => $r['Status'] === 'solved'));
fputcsv($output, ['Solved', $solved]);
fputcsv($output, ['Open', count($rows) - $solved]);
$hours = array_filter(array_column($rows, 'Resolution Hours'), fn($h) => $h !== null);
$avgHrs = !empty($hours) ? round(array_sum($hours) / count($hours), 1) : 'N/A';
fputcsv($output, ['Avg Resolution Hours', $avgHrs]);
fputcsv($output, ['Generated', date('d M Y, h:i A')]);
fputcsv($output, ['Generated By', $_SESSION['staff_name'] ?? 'ICT Head']);

fclose($output);
exit;
