-- ============================================================
-- Security Migration: Run this ONCE on an existing database
-- Adds: admin role, login_attempts table
-- ============================================================

USE tms_apollo;

-- 1. Add 'admin' to the it_staff role ENUM
ALTER TABLE it_staff
  MODIFY COLUMN role ENUM('admin','ict_head','assistant_manager','assistant_ict','sr_it_executive','assistant_it') NOT NULL;

-- 2. Create login_attempts table for DB-backed brute-force protection
CREATE TABLE IF NOT EXISTS login_attempts (
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ip_address   VARCHAR(45) NOT NULL,
    email        VARCHAR(150) NOT NULL,
    attempted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ip_email (ip_address, email),
    INDEX idx_attempted (attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Insert System Admin account (password: Apollo@2026!)
--    BCrypt hash must be generated by seed.php — this is a placeholder.
--    If you haven't re-run seed.php, run it to create this account.
--    Or manually insert with a bcrypt hash from PHP:
--    php -r "echo password_hash('Apollo@2026!', PASSWORD_BCRYPT, ['cost'=>12]);"
INSERT INTO it_staff (name, email, password_hash, role, designation, contact)
SELECT 'System Admin', 'tms@apollouniversity.edu.in',
       '$2y$12$placeholder_migrate_run_seed_php', 'admin', 'System Administrator', '0000000000'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM it_staff WHERE email = 'tms@apollouniversity.edu.in'
);
