-- ============================================================
-- Apollo University TMS - Seed Data
-- Run AFTER schema.sql
-- Default staff password: Apollo@2026!
-- BCrypt hash generated by seed.php
-- ============================================================

USE tms_apollo;

-- ============================================================
-- IT Staff (passwords set via seed.php which bcrypt-hashes them)
-- ============================================================
INSERT INTO it_staff (name, email, password_hash, role, designation, contact) VALUES
('Dr. Ramesh Kumar',  'ramesh.kumar@apollouniversity.edu.in',  '$2y$12$placeholder_hash_1_replace', 'ict_head',          'ICT Head',           '9876543210'),
('Ms. Priya Sharma',  'priya.sharma@apollouniversity.edu.in',  '$2y$12$placeholder_hash_2_replace', 'ict_head',          'Assistant ICT',      '9876543211'),
('Mr. Arun Verma',    'arun.verma@apollouniversity.edu.in',    '$2y$12$placeholder_hash_3_replace', 'assistant_manager', 'Assistant Manager',  '9876543212'),
('Mr. Kiran Patel',   'kiran.patel@apollouniversity.edu.in',   '$2y$12$placeholder_hash_4_replace', 'sr_it_executive',   'Sr. IT Executive',   '9876543213'),
('Mr. Suresh Reddy',  'suresh.reddy@apollouniversity.edu.in',  '$2y$12$placeholder_hash_5_replace', 'sr_it_executive',   'Sr. IT Executive',   '9876543214'),
('Ms. Deepa Nair',    'deepa.nair@apollouniversity.edu.in',    '$2y$12$placeholder_hash_6_replace', 'sr_it_executive',   'Sr. IT Executive',   '9876543215');

-- ============================================================
-- Problem Categories
-- ============================================================
INSERT INTO problem_categories (name, icon, description) VALUES
('WiFi Signal Weak / Slow',          'bi-wifi',               'Poor or unstable wireless connectivity'),
('No Internet Connectivity',         'bi-wifi-off',           'Complete loss of internet access'),
('Computer / Laptop Not Working',    'bi-pc-display',         'Hardware or operating system level issues'),
('Printer Issue',                    'bi-printer',            'Printing errors, paper jams, driver issues'),
('Email / Account Login Problem',    'bi-envelope-slash',     'Cannot log in to email or university accounts'),
('Software Installation Required',   'bi-box-arrow-in-down',  'Need new or updated software installed'),
('Power / Electricity Issue',        'bi-plug',               'Power socket, UPS, or surge issues'),
('Projector / Display Problem',      'bi-projector',          'Projector not working, display errors'),
('Network / LAN Issue',              'bi-hdd-network',        'Wired network / LAN connectivity problems'),
('Other',                            'bi-question-circle',    'Any other issue not listed above');
